### PR TITLE
deps:replace native-or-bluebird with any-promise

### PR DESCRIPTION
**Pull request by ngot**
deprecate: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.

### CODE REVIEW

**Comment by dead-horse** [comment]
LGTM

**Comment by dead-horse** [comment]
@jonathanong don't have permission to publish.

**Comment by ngot** [comment]
There are a lot module to be updated .Can add me to this group?

**Comment by jonathanong** [comment]
sorry missed this. added @dead-horse on npm and added @ngot to the org

**Comment by ngot** [comment]
@dead-horse need to push to npm.

**Comment by dead-horse** [comment]
done

**Pull request merged**
